// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoSaveController from "./auto_save_controller"
application.register("auto-save", AutoSaveController)

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import ChatKeyboardController from "./chat_keyboard_controller"
application.register("chat-keyboard", ChatKeyboardController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import CollaborationController from "./collaboration_controller"
application.register("collaboration", CollaborationController)

import ConnectionStatusController from "./connection_status_controller"
application.register("connection-status", ConnectionStatusController)

import CustomSelectController from "./custom_select_controller"
application.register("custom-select", CustomSelectController)

import DashboardActionController from "./dashboard_action_controller"
application.register("dashboard-action", DashboardActionController)

import DashboardChatInputController from "./dashboard_chat_input_controller"
application.register("dashboard-chat-input", DashboardChatInputController)

import DashboardChatScrollController from "./dashboard_chat_scroll_controller"
application.register("dashboard-chat-scroll", DashboardChatScrollController)

import DateCalculatorController from "./date_calculator_controller"
application.register("date-calculator", DateCalculatorController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import ErrorHandlerController from "./error_handler_controller"
application.register("error-handler", ErrorHandlerController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import InlineEditController from "./inline_edit_controller"
application.register("inline-edit", InlineEditController)

import InvitationFilterController from "./invitation_filter_controller"
application.register("invitation-filter", InvitationFilterController)

import KanbanController from "./kanban_controller"
application.register("kanban", KanbanController)

import KeyboardShortcutsController from "./keyboard_shortcuts_controller"
application.register("keyboard-shortcuts", KeyboardShortcutsController)

import ListFilterController from "./list_filter_controller"
application.register("list-filter", ListFilterController)

import MarkdownController from "./markdown_controller"
application.register("markdown", MarkdownController)

import MarkdownMessageController from "./markdown_message_controller"
application.register("markdown-message", MarkdownMessageController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ModalOpenerController from "./modal_opener_controller"
application.register("modal-opener", ModalOpenerController)

import NotificationFiltersController from "./notification_filters_controller"
application.register("notification-filters", NotificationFiltersController)

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)

import ProgressAnimationController from "./progress_animation_controller"
application.register("progress-animation", ProgressAnimationController)

import QuickAddController from "./quick_add_controller"
application.register("quick-add", QuickAddController)

import RealtimeController from "./realtime_controller"
application.register("realtime", RealtimeController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import UserFilterController from "./user_filter_controller"
application.register("user-filter", UserFilterController)

import WysiwygMarkdownController from "./wysiwyg_markdown_controller"
application.register("wysiwyg-markdown", WysiwygMarkdownController)
