// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoSaveController from "./auto_save_controller"
application.register("auto-save", AutoSaveController)

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import CollaborationController from "./collaboration_controller"
application.register("collaboration", CollaborationController)

import CustomSelectController from "./custom_select_controller"
application.register("custom-select", CustomSelectController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FiltersController from "./filters_controller"
application.register("filters", FiltersController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import InlineEditController from "./inline_edit_controller"
application.register("inline-edit", InlineEditController)

import KeyboardShortcutsController from "./keyboard_shortcuts_controller"
application.register("keyboard-shortcuts", KeyboardShortcutsController)

import ListManagementController from "./list_management_controller"
application.register("list-management", ListManagementController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NotificationFiltersController from "./notification_filters_controller"
application.register("notification-filters", NotificationFiltersController)

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)

import ProgressAnimationController from "./progress_animation_controller"
application.register("progress-animation", ProgressAnimationController)

import QuickAddController from "./quick_add_controller"
application.register("quick-add", QuickAddController)

import RealtimeController from "./realtime_controller"
application.register("realtime", RealtimeController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
